version: '2'

services:
  test-gpu:
     build:
       context: . 
     volumes:
        - ./:/workspace/
     command: bash -c "
           cd /workspace
           && pytest ./"
          
  py3:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
       - ./:/workspace/
    command: sleep infinity