version: '2'

services:
  # test:
  #   build:
  #     context: . 
  #   volumes:
  #      - ./:/workspace/
  #   command: bash -c "
  #         cd /workspace
  #         && python3 test/test_basic.py"
          
  py3:
    image: python:3
    volumes:
       - ./:/workspace/
    command: sleep infinity