version: '2'

services:
  hub:
    build:
      context: . 
    volumes:
       - ./:/workspace/
    command: bash -c "
          cd /workspace
          && hub configure
          && python3 example.py"
  prod:
    image: python:3
    volumes:
       - ./:/workspace/
    command: bash -c "
          cd /workspace
          && ls
          && pip3 install hub-array-beta
          && hub configure"