title: Snark AI
description: test description
themeConfig:
  logo: /logo.svg
  nav:
    - text: 'Blog'
      link: 'https://blog.snark.ai'
    - text: 'Docs'
      link: 'https://docs.snark.ai'
  sidebar:
    - title:
      children:
        - title: Getting Started
          to: /
    - title: Guide
      children:
        - title: Experiments
          to: /guide/experiments.html
        - title: Monitoring
          to: /guide/monitoring.html
        - title: Store
          to: /guide/store.html
        - title: Troubleshooting
          to: /guide/troubleshooting.html
    - title: Use Cases
      children:
        - title: Hyperparameter
          to: /use-cases/hyperparameter.html
        - title: Jupyter Lab
          to: /use-cases/jupyter-lab.html